### ISSUE TITLE
Error with locale

### ISSUE THREAD

**Issue by akhamar** [Arksine/CanBoot#64]
I recently updated the project and I'm facing this issue while trying to do a `make menuconfig`

```
master ✔ $ make menuconfig 
Using default symbol values (no '/tmp/CanBoot/.config')
Configuration saved to '/tmp/CanBoot/.config'
  Creating symbolic link out/board
Loaded configuration '/tmp/CanBoot/.config'
Traceback (most recent call last):
  File "lib/kconfiglib/menuconfig.py", line 3281, in <module>
    _main()
  File "lib/kconfiglib/menuconfig.py", line 661, in _main
    menuconfig(standard_kconfig(__doc__))
  File "lib/kconfiglib/menuconfig.py", line 705, in menuconfig
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
make: *** [Makefile:150: menuconfig] Error 1
```

**Comment by akhamar** [comment]
Solved with a `dpkg-reconfigure locales`
